language: php
php:
  - 5.5
  - 5.6
env:
  - SYMFONY_VERSION="2.6.*"

cache:
  directories:
    - $HOME/.composer/cache

# Set up the project for testing
before_install:
  - echo "memory_limit=2560M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist

# Run Tests
script:
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover

# Process results
after_script:
  # Send code coverage to scrutinizer-ci.com & coveralls.io
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover  build/logs/clover.xml

# Build Matrix
matrix:
  fast_finish: true
  allow_failures:
    - env: SYMFONY_VERSION="2.7.*@dev"
  include:
    - php: 5.4
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*@dev"

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
